<!DOCTYPE html>
<html>
	<head>
		<title>Fosterhome Animal Insert Validation</title>
	</head>
	<body>
		<h2>Fosterhome Animal Insert Validation (Trigger)</h2>
		<h4>Author: Denis Roman</h4>
		<p><b>Description:</b> This page demonstrates that the fosterhome_animal_BEFORE_INSERT trigger is functioning correctly.
		This trigger ensures that a foster home's maximum number of animals is not exceeded when creating a fosterhome_animal record.</p>
		<p><b>Justification:</b> A foster home cannot foster more animals than its stated maximum capacity. This trigger enforces that.</p>
		<p><b>Expected Execution:</b> Input the data for a new fosterhome_animal record to be inserted into the database. Try inserting
		a record with a Foster Animal ID of 301, an Animal ID of 90, a Foster ID of 100, and any date. The insert should be successful
		and its data displayed. The foster home with a Foster ID of 100 is now at max capacity (2 animals). Now try inserting a record
		with a Foster Animal ID of 302, an Animal ID of 91, a Foster ID of 100, and any date. This will fail and give the appropriate
		error message generated by the trigger.</p>
		
		<p>Please enter the following information for the new fosterhome_animal entity:</p>
		
		<form method="post">
			<label for="foster_animal_ID">Foster Animal ID: </label>
			<input type="number" name="foster_animal_ID" id="foster_animal_ID" />
			<br />
<?php
// pre-populate part of the form
require_once '../dbconfig-paws.php';
error_reporting(E_ERROR | E_WARNING | E_PARSE | E_NOTICE);
ini_set('display_errors', '1');

$sql = new mysqli($hostname, $username, $password, $schema);
if ($sql->connect_errno) {
	echo 'Connection failed: ' . $sql->connect_errno;
} else {
	
	// animal_ID
	$sqlquery = 'SELECT animal_ID FROM animal';
	$result = $sql->query($sqlquery);
	if ($result) {
		echo '<label for="animal_ID">Animal ID: </label>';
		echo '<select name="animal_ID" id="animal_ID">';
		while ($row = $result->fetch_assoc()) {
			$animal_ID = $row['animal_ID'];
			echo '<option value="' . $animal_ID . '">' . $animal_ID . '</option>';
		}
		
		echo '</select>';
	} else {
		echo 'Connection failed: ' . $sql->connect_errno;
	}
	
	echo '<br />';
	
	// foster_ID
	$sqlquery = 'SELECT foster_ID FROM fosterhome';
	$result = $sql->query($sqlquery);
	if ($result) {
		echo '<label for="foster_ID">Foster ID: </label>';
		echo '<select name="foster_ID" id="foster_ID">';
		while ($row = $result->fetch_assoc()) {
			$foster_ID = $row['foster_ID'];
			echo '<option value="' . $foster_ID . '">' . $foster_ID . '</option>';
		}
		
		echo '</select>';
	} else {
		echo 'Connection failed: ' . $sql->connect_errno;
	}
	
	
}
?>
			<br />
			<label for="foster_date">Foster Date: </label>
			<input type="date" name="foster_date" id="foster_date" />
			<br />
			<input type="submit" value="Insert" />
		</form>


<?php
require_once '../dbconfig-paws.php';
error_reporting(E_ERROR | E_WARNING | E_PARSE | E_NOTICE);
ini_set('display_errors', '1');

if ($_SERVER['REQUEST_METHOD'] == 'POST') {
	
	$foster_animal_ID = $_POST['foster_animal_ID'];
	$animal_ID = $_POST['animal_ID'];
	$foster_ID = $_POST['foster_ID'];
	$foster_date = $_POST['foster_date'];
	
	$sql = new mysqli($hostname, $username, $password, $schema);
	if ($sql->connect_errno) {
		echo 'Connection failed: ' . $sql->connect_errno;
	} else {
		$sqlquery = 'INSERT INTO fosterhome_animal (foster_animal_ID, animal_ID, foster_ID, foster_date)
						VALUES (' . $sql->real_escape_string($foster_animal_ID) . ',
						' . $sql->real_escape_string($animal_ID) . ',
						' . $sql->real_escape_string($foster_ID) . ",
						STR_TO_DATE('" . $sql->real_escape_string($foster_date) . "', '%Y-%m-%d'));";
		
		if ($sql->query($sqlquery)) {
			// insert successful
			
			$sqlquery = 'SELECT foster_animal_ID, animal_ID, foster_ID, foster_date FROM fosterhome_animal
							WHERE foster_animal_ID = ' . $sql->real_escape_string($foster_animal_ID) . ';';
		
			$result = $sql->query($sqlquery);
			
			if ($result) {
				
				// fetch single result
				$row = $result->fetch_assoc();
				
				echo '<p>Foster Animal ID: ' . $row['foster_animal_ID'] . '</p>';
				echo '<p>Animal ID: ' . $row['animal_ID'] . '</p>';
				echo '<p>Foster ID: ' . $row['foster_ID'] . '</p>';
				echo '<p>Foster Date: ' . $row['foster_date'] . '</p>';
				
				$result->free_result();
				
			} else {
				echo '<p>' . $sql->error . '</p>';
			}
		} else {
			echo '<p>' . $sql->error . '</p>';
		}
		
		$sql->close();
	}
}
?>
	</body>
</html>
